name: Build
on: [push]
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - run: choco install nuget.commandline

    - run: choco install curl

    - name: Download info about the last package
      run: 'curl --silent -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://nuget.pkg.github.com/oledid/oledid.SyntaxImprovement/index.json" > nuget-index.json'

    - name: Prepare version
      run: pwsh prepare-version.ps1 -commitish ${{ github.sha }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Publish test-exe
      run: dotnet publish .\src\SyntaxImprovement.Tests\SyntaxImprovement.Tests.csproj --self-contained --runtime win-x64 /p:UseAppHost=true

    - name: Test with dotnet
      run: dotnet test --no-build .\src\SyntaxImprovement.Tests\SyntaxImprovement.Tests.csproj

    - name: Add NuGet source
      run: nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/oledid/index.json" -UserName oledid -Password ${{ secrets.GITHUB_TOKEN }}

    - name: NuGet pack
      run: pwsh ./NuGet/pack.ps1

    - name: Push to GitHub packages
      run: nuget push "oledid.SyntaxImprovement.*.nupkg" -Source "https://nuget.pkg.github.com/oledid/index.json"

    - name: Create release
      run: 'curl --silent -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/x-www-form-urlencoded" -d "@release-request.json" -X POST "https://api.github.com/repos/oledid/oledid.SyntaxImprovement/releases" > nul'

